version: '3'
services:
  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    env_file: ./todo-backend/.env
    ports:
      - 3000:3000
    depends_on:
      - todo-db

  todo-db:
    build:
      context: ./todo-db
      dockerfile: Dockerfile
    env_file: ./todo-db/.env
    ports:
      - 3001:3001
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: